server:
  port: 9201
spring:
  application:
    name: user-shop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    url: jdbc:mysql://106.13.117.43:3306/shop
    username: root
    password: asdasd
    type: 
  jpa:
    properties:
    hibernate:
      ddl-auto: update
    # 展示sql
    show-sql: true
  jooq:
    sql-dialect: org.hi